package com.forealert.intf.temp.entity;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize.Inclusion;
import com.forealert.intf.Constant;

import javax.xml.bind.annotation.XmlRootElement;
import java.util.Date;
import java.util.TimeZone;

@JsonSerialize(include = Inclusion.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
@XmlRootElement(name = "Community_Group_Files")
@DynamoDBTable(tableName="Community_Group_Files")
public class CommunityGroupFiles {

	private String groupFileId;
	private String groupId;
	private String fileType;
	private String fileTitle;
	private String fileIconUrl;
	private String fileDescription;
	private String fileUploadedByUuid;
	private String fileLocation;
	private String createdDate;
	private String lastModifiedDate;
	
	
	@DynamoDBHashKey(attributeName="GFId")
	@DynamoDBAutoGeneratedKey
	public String getGroupFileId() {
		return groupFileId;
	}
	public void setGroupFileId(String groupFileId) {
		this.groupFileId = groupFileId;
	}
	
	@DynamoDBIndexHashKey(globalSecondaryIndexName = "GId-FUUuid-index", attributeName = "GId")
	@DynamoDBRangeKey(attributeName="GId")
	public String getGroupId() {
		return groupId;
	}
	public void setGroupId(String groupId) {
		this.groupId = groupId;
	}
	
	
	@DynamoDBAttribute(attributeName="FT")
	public String getFileType() {
		return fileType;
	}
	public void setFileType(String fileType) {
		this.fileType = fileType;
	}
	
	@DynamoDBAttribute(attributeName="FTTL")
	public String getFileTitle() {
		return fileTitle;
	}
	public void setFileTitle(String fileTitle) {
		this.fileTitle = fileTitle;
	}
	
	@DynamoDBAttribute(attributeName="FD")
	public String getFileDescription() {
		return fileDescription;
	}
	public void setFileDescription(String fileDescription) {
		this.fileDescription = fileDescription;
	}
	
	@DynamoDBAttribute(attributeName="FIUrl")
	public String getFileIconUrl() {
		return fileIconUrl;
	}
	public void setFileIconUrl(String fileIconUrl) {
		this.fileIconUrl = fileIconUrl;
	}
	
	@DynamoDBIndexRangeKey(globalSecondaryIndexName = "GId-FUUuid-index", attributeName = "FUUuid")
	public String getFileUploadedByUuid() {
		return fileUploadedByUuid;
	}
	public void setFileUploadedByUuid(String fileUploadedByUuid) {
		this.fileUploadedByUuid = fileUploadedByUuid;
	}
	
	@DynamoDBAttribute(attributeName="FL")
	public String getFileLocation() {
		return fileLocation;
	}
	public void setFileLocation(String fileLocation) {
		this.fileLocation = fileLocation;
	}
	
	
	@DynamoDBAttribute(attributeName="CRD")
	public String getCreatedDate() {
		return createdDate;
	}
	public void setCreatedDate(Date createdDate) {
		if(createdDate == null) createdDate = new Date();
		Constant.dateFormatter.setTimeZone(TimeZone.getTimeZone("UTC"));
		this.createdDate = Constant.dateFormatter.format(createdDate);

	}

	@DynamoDBAttribute(attributeName="LMD")
	public String getLastModifiedDate() {
		return lastModifiedDate;
	}
	public void setLastModifiedDate(Date lastModifiedDate) {
		if(lastModifiedDate == null) lastModifiedDate = new Date();

        Constant.dateFormatter.setTimeZone(TimeZone.getTimeZone("UTC"));
		this.lastModifiedDate = Constant.dateFormatter.format(lastModifiedDate);

	}
	public void setCreatedDate(String createdDate) {
		this.createdDate = createdDate;
	}
	public void setLastModifiedDate(String lastModifiedDate) {
		this.lastModifiedDate = lastModifiedDate;
	}
	
	
}
